package load;

import config.ClientConfigurationFactory;
import org.apache.ignite.Ignite;
import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (‎11‎/‎14‎/‎2017‎ ‎16‎:‎50) **/
public class LoadCaches {
    /**
     * <p>
     * Utility to load caches from database.
     * <p>
     * How to use:
     * <ul>
     *     <li>Start cluster.</li>
     *     <li>Start this utility and wait while load complete.</li>
     * </ul>
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        // Ignite ignite = Ignition.start("Persons-client.xml")
        try (Ignite ignite = Ignition.start(ClientConfigurationFactory.createConfiguration())) {
            System.out.println(">>> Loading caches...");
            System.out.println(">>> Loading cache: PersonCache");
            ignite.cache("PersonCache").loadCache(null);

            System.out.println(">>> All caches loaded!");
        }
    }
}